#sdk: "C:/RhoStudio/ruby/lib/ruby/gems/1.8/gems/rhodes-3.3.2"
sdkversion: 3.3.2
name: MobileMaintenanceClient
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.mobilemaintenanceclient
  BundleURLScheme: mobilemaintenanceclient
wp:
  productid: 9b6d66c0-774d-012f-b35d-00ff4ca6112f
symbian:
  uid: 0xe7a07eb9
android:
  version: 2.1
  emulator: RhoEmu32
extensions:
  - json
  - another-extension
