#Sources 
:sources: 
  OrderDetail: 
    :poll_interval: 300
  ServiceOrder: 
    :poll_interval: 300
 
:development: 
  :syncserver: http://localhost:9292/api/application/
  :licensefile: settings/license.key
  :redis: localhost:6379
:production: 
  :syncserver: http://localhost:9292/api/application/
  :licensefile: settings/license.key
  :redis: localhost:6379
:test: 
  :syncserver: http://localhost:9292/api/application/
  :licensefile: settings/license.key
  :redis: localhost:6379
